### ISSUE TITLE
Documentation Mismatch With Code

### ISSUE THREAD

**Issue by mikaelsnavy** [erikhoward/flask-keyvault#1]
README.md has `from flask_keyvault import AzureKeyVault` and `keyvault = AzureKeyVault()` however I believe that instead of `AzureKeyVault` the docs should match the object inside \_\_init\_\_.py and be just `KeyVault`.

Mind if I submit a PR to fix this?

**Comment by erikhoward** [comment]
Thanks for finding that. Sure, go ahead and submit a PR.
