### ISSUE TITLE
Listing Secrets in a Key Vault

### ISSUE THREAD

**Issue by mikaelsnavy** [erikhoward/flask-keyvault#3]
Hello!

I can see a use for getting all secrets in a certain Key Vault (for example, bringing in all secrets as application configuration in Flask). Currently, `flask-keyvault` only supports single secret get/set operations. Any objections to me implementing a `list` method that just uses `azure.keyvault.KeyVaultClient.get_secrets` under the hood?

Thanks! :smile:

**Comment by erikhoward** [comment]
Added support for get_secrets call in commit in changest [831cc18](https://github.com/erikhoward/flask-keyvault/commit/831cc18bea2f1eb85d81e272157c2ce4c3be4bc1).
